### ISSUE TITLE
Configure CI/CD pipeline

### ISSUE THREAD

**Issue by valtterikantanen** [UniversityOfHelsinkiCS/distributed-file-system#6]
We need to build a new image and push it to DockerHub after the tests have been run successfully.

**Comment by evahteri** [comment]
Related PR: https://github.com/UniversityOfHelsinkiCS/distributed-file-system/pull/8
Deploy is still failing, because it cannot reach the secrets for some reason. need to investigate why
![Screenshot from 2024-11-23 16-20-57](https://github.com/user-attachments/assets/a73c74d1-7cde-43e3-8064-a49cf3994619)

**Comment by valtterikantanen** [comment]
There seems to be a small typo in the workflow file:

https://github.com/UniversityOfHelsinkiCS/distributed-file-system/blob/ac482fc69876eb2cdaf3bcd97da3552235ef41da/.github/workflows/deploy.yml#L14-L16

The secrets are actually `DOCKER_HUB_USER` and `DOCKER_HUB_TOKEN`

**Comment by evahteri** [comment]
Pipelines and initial tests done, closing as done
